Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Recursos_Humanos.Data;
using Recursos_Humanos.Models;

namespace Recursos_Humanos.Controllers
{
    [Authorize(Roles = "Administrador de Recursos Humanos,Gestor de Personal,Jefe de Departamento,Empleado")]
    public class EmpleadosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmpleadosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Empleados
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Empleados.Include(e => e.Departamento);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Empleados/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleadosModel = await _context.Empleados
                .Include(e => e.Departamento)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (empleadosModel == null)
            {
                return NotFound();
            }

            return View(empleadosModel);
        }

        // GET: Empleados/Create
        public IActionResult Create()
        {
            ViewData["DepartamentoId"] = new SelectList(_context.Departamentos, "Id", "Nombre");
            return View();
        }

        // POST: Empleados/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Puesto,DepartamentoId,Salario")] EmpleadosModel empleadosModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(empleadosModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartamentoId"] = new SelectList(_context.Departamentos, "Id", "Nombre", empleadosModel.DepartamentoId);
            return View(empleadosModel);
        }

        // GET: Empleados/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleadosModel = await _context.Empleados.FindAsync(id);
            if (empleadosModel == null)
            {
                return NotFound();
            }
            ViewData["DepartamentoId"] = new SelectList(_context.Departamentos, "Id", "Nombre", empleadosModel.DepartamentoId);
            return View(empleadosModel);
        }

        // POST: Empleados/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Puesto,DepartamentoId,Salario")] EmpleadosModel empleadosModel)
        {
            if (id != empleadosModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empleadosModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpleadosModelExists(empleadosModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartamentoId"] = new SelectList(_context.Departamentos, "Id", "Nombre", empleadosModel.DepartamentoId);
            return View(empleadosModel);
        }

        // GET: Empleados/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleadosModel = await _context.Empleados
                .Include(e => e.Departamento)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (empleadosModel == null)
            {
                return NotFound();
            }

            return View(empleadosModel);
        }

        // POST: Empleados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var empleadosModel = await _context.Empleados.FindAsync(id);
            if (empleadosModel != null)
            {
                _context.Empleados.Remove(empleadosModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpleadosModelExists(int id)
        {
            return _context.Empleados.Any(e => e.Id == id);
        }
    }
}

Controllers/EvaluadoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Recursos_Humanos.Data;
using Recursos_Humanos.Models;

namespace Recursos_Humanos.Controllers
{
    [Authorize(Roles = "Administrador de Recursos Humanos")]
    public class EvaluadoresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EvaluadoresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Evaluadores
        public async Task<IActionResult> Index()
        {
            return View(await _context.Evaluadores.ToListAsync());
        }

        // GET: Evaluadores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evaluadoresModel = await _context.Evaluadores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (evaluadoresModel == null)
            {
                return NotFound();
            }

            return View(evaluadoresModel);
        }

        // GET: Evaluadores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Evaluadores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Cargo,Email")] EvaluadoresModel evaluadoresModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(evaluadoresModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(evaluadoresModel);
        }

        // GET: Evaluadores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evaluadoresModel = await _context.Evaluadores.FindAsync(id);
            if (evaluadoresModel == null)
            {
                return NotFound();
            }
            return View(evaluadoresModel);
        }

        // POST: Evaluadores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Cargo,Email")] EvaluadoresModel evaluadoresModel)
        {
            if (id != evaluadoresModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(evaluadoresModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EvaluadoresModelExists(evaluadoresModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(evaluadoresModel);
        }

        // GET: Evaluadores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evaluadoresModel = await _context.Evaluadores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (evaluadoresModel == null)
            {
                return NotFound();
            }

            return View(evaluadoresModel);
        }

        // POST: Evaluadores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var evaluadoresModel = await _context.Evaluadores.FindAsync(id);
            if (evaluadoresModel != null)
            {
                _context.Evaluadores.Remove(evaluadoresModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EvaluadoresModelExists(int id)
        {
            return _context.Evaluadores.Any(e => e.Id == id);
        }
    }
}

Controllers/SalariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Recursos_Humanos.Data;
using Recursos_Humanos.Models;

namespace Recursos_Humanos.Controllers
{
    [Authorize(Roles = "Administrador de Recursos Humanos,Gestor de Personal,Jefe de Departamento,Empleado")]
    public class SalariosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SalariosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Salarios
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Salarios.Include(s => s.Empleado);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Salarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salariosModel = await _context.Salarios
                .Include(s => s.Empleado)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (salariosModel == null)
            {
                return NotFound();
            }

            return View(salariosModel);
        }
        [Authorize(Roles = "Administrador de Recursos Humanos")]
        // GET: Salarios/Create
        public IActionResult Create()
        {
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "Id", "Id");
            return View();
        }
        [Authorize(Roles = "Administrador de Recursos Humanos")]
        // POST: Salarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,EmpleadoId,Monto,FechaVigencia")] SalariosModel salariosModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(salariosModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "Id", "Id", salariosModel.EmpleadoId);
            return View(salariosModel);
        }
        [Authorize(Roles = "Administrador de Recursos Humanos")]
        // GET: Salarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salariosModel = await _context.Salarios.FindAsync(id);
            if (salariosModel == null)
            {
                return NotFound();
            }
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "Id", "Id", salariosModel.EmpleadoId);
            return View(salariosModel);
        }
        [Authorize(Roles = "Administrador de Recursos Humanos")]
        // POST: Salarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EmpleadoId,Monto,FechaVigencia")] SalariosModel salariosModel)
        {
            if (id != salariosModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(salariosModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalariosModelExists(salariosModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "Id", "Id", salariosModel.EmpleadoId);
            return View(salariosModel);
        }
        [Authorize(Roles = "Administrador de Recursos Humanos")]
        // GET: Salarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salariosModel = await _context.Salarios
                .Include(s => s.Empleado)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (salariosModel == null)
            {
                return NotFound();
            }

            return View(salariosModel);
        }
        [Authorize(Roles = "Administrador de Recursos Humanos")]
        // POST: Salarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var salariosModel = await _context.Salarios.FindAsync(id);
            if (salariosModel != null)
            {
                _context.Salarios.Remove(salariosModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SalariosModelExists(int id)
        {
            return _context.Salarios.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Recursos_Humanos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Recursos_Humanos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Recursos_Humanos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                       

                        <!-- Menú accesible solo para Administradores de Recursos Humanos -->
                        @if (User.IsInRole("Administrador de Recursos Humanos"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Departamentos" asp-action="Index">Departamentos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="Index">Empleados</a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Evaluadores" asp-action="Index">Evaluadores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Salarios" asp-action="Index">Salarios</a>
                            </li>
                        }

                        <!-- Menú solo visible para Gestores de Personal -->
                        @if (User.IsInRole("Gestor de Personal"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Evaluaciones" asp-action="Index">Evaluaciones</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Evaluadores" asp-action="Index">Evaluadores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Salarios" asp-action="Index">Salarios</a>
                            </li>
                        }

                        <!-- Menú solo visible para Jefes de Departamento -->
                        @if (User.IsInRole("Jefe de Departamento"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Evaluaciones" asp-action="Index">Mis Evaluaciones</a>
                            </li>
                        }

                        <!-- Menú solo visible para Empleados -->
                        @if (User.IsInRole("Empleado"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Evaluaciones" asp-action="Index">Mis Evaluaciones</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Salarios" asp-action="Index">Salarios</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Recursos_Humanos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>